apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qfoq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0031-tenant/tkrw-pr712-0075-0031-app/devfile-sample-qfoq@sha256:10235d4e44db00f9e76500f70446ef223a55e9647faddf095e032b753808ef42
        name: my-nodejs
        resources: {}
status: {}
